package net.tyler.tutorialmod.entity.client;

import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;

public class HamsterAnimations {


    public static final Animation ANIM_HAMSTER_IDLE = Animation.Builder.create(2f).looping()
            .addBoneAnimation("body",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.41667f, AnimationHelper.createTranslationalVector(0f, 0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.91667f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.41667f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("head",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.54167f, AnimationHelper.createRotationalVector(0f, 0f, -5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(-0.03f, -0.67f, 4.95f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("tail",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.54167f, AnimationHelper.createRotationalVector(0f, 10f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(0f, -10f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR))).build();
    public static final Animation ANIM_HAMSTER_WALK = Animation.Builder.create(2f).looping()
            .addBoneAnimation("body",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("body",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, -5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 5f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("head",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(0f, 0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createTranslationalVector(0f, -0.1f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("tail",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, -5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(0f, 5f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leftleg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("rightleg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.25f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.75f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leftleg2",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.25f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.75f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("rightleg2",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.25f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.75f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR))).build();


    public static final Animation ANIM_HAMSTER_PLAYDEAD = Animation.Builder.create(6.5f)
            .addBoneAnimation("body",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("body",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(-129.32f, 23.93f, 26.34f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(-179.11f, 24.29f, -0.09f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("head",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(2f, 0.1f, 4.8f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(1.2f, -2.9f, 5.5f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("head",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(-129.32f, 23.93f, 26.34f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(-179.11f, 24.29f, -0.09f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("frontleg1",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(1.9f, 5.2f, 4.1f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(1.5f, 3.2f, 6.6f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("frontleg1",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(-129.32f, 23.93f, 26.34f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(-179.11f, 24.29f, -0.09f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("backleg",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(-2f, 1.4f, -6.9f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(-1.4f, 3.1f, -6.65f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("backleg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(-129.32f, 23.93f, 26.34f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(-179.11f, 24.29f, -0.09f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("tail",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(-2f, -5.4f, -4.5f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createTranslationalVector(-1.6f, -5.4f, -7f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("tail",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(-129.32f, 23.93f, 26.34f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(-179.11f, 24.29f, -0.09f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leftleg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(1f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.25f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.75f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.25f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.5f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.5f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(4f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(4.5f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(5.5f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(6.5f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("rightleg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(1f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.25f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.75f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.25f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.5f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.5f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(4f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(4.5f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(5.5f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(6.5f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("rightleg2",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(1f, AnimationHelper.createRotationalVector(5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.25f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.75f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.25f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.5f, AnimationHelper.createRotationalVector(5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.5f, AnimationHelper.createRotationalVector(5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(4f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(4.5f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(5.5f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(6.5f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leftleg2",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(1f, AnimationHelper.createRotationalVector(-12.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.25f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(-12.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.75f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(-12.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.25f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.5f, AnimationHelper.createRotationalVector(-12.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.5f, AnimationHelper.createRotationalVector(-12.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(4f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(4.5f, AnimationHelper.createRotationalVector(-12.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(5.5f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(6.5f, AnimationHelper.createRotationalVector(-12.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR))).build();


    public static final Animation ANIM_HAMSTER_SIT = Animation.Builder.create(0f).looping()
            .addBoneAnimation("body",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(-75f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("head",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 2.6f, 2.7f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("head",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(-42.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leftleg",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 4f, 1f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leftleg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(-75f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("rightleg",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 4f, 1f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("rightleg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(-75f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("rightleg2",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -1f, -5f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("rightleg2",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(-75f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leftleg2",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -1f, -5f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("leftleg2",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(-75f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("tail",
                    new Transformation(Transformation.Targets.TRANSLATE,
                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, -5f, -2f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("tail",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(30f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR))).build();
}
    // scary dismembered one from claude
//    public static final Animation ANIM_HAMSTER_PLAYDEAD = Animation.Builder.create(6.5f)
//            .addBoneAnimation("leftleg",
//                    new Transformation(Transformation.Targets.ROTATE,
//                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1.25f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1.75f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(2f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(2.25f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(2.5f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(3f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(3.5f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(4f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(4.5f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(5.5f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(6.5f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR)))
//            .addBoneAnimation("rightleg",
//                    new Transformation(Transformation.Targets.ROTATE,
//                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1.25f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1.75f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(2f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(2.25f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(2.5f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(3f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(3.5f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(4f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(4.5f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(5.5f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(6.5f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR)))
//            .addBoneAnimation("rightleg2",
//                    new Transformation(Transformation.Targets.ROTATE,
//                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1f, AnimationHelper.createRotationalVector(5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1.25f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1.75f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(2f, AnimationHelper.createRotationalVector(5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(2.25f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(2.5f, AnimationHelper.createRotationalVector(5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(3f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(3.5f, AnimationHelper.createRotationalVector(5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(4f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(4.5f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(5.5f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(6.5f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR)))
//            .addBoneAnimation("leftleg2",
//                    new Transformation(Transformation.Targets.ROTATE,
//                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1f, AnimationHelper.createRotationalVector(-12.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1.25f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(-12.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1.75f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(2f, AnimationHelper.createRotationalVector(-12.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(2.25f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(2.5f, AnimationHelper.createRotationalVector(-12.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(3f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(3.5f, AnimationHelper.createRotationalVector(-12.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(4f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(4.5f, AnimationHelper.createRotationalVector(-12.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(5.5f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(6.5f, AnimationHelper.createRotationalVector(-12.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR)))
//            .addBoneAnimation("hamster",
//                    new Transformation(Transformation.Targets.TRANSLATE,
//                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
//                                    Transformation.Interpolations.LINEAR)))
//            .addBoneAnimation("hamster",
//                    new Transformation(Transformation.Targets.ROTATE,
//                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(-119.05f, 20.44f, 32.15f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1f, AnimationHelper.createRotationalVector(-179.11f, 24.29f, -0.09f),
//                                    Transformation.Interpolations.LINEAR))).build();


    // decapitated looking one (later one where i tried to make the legs transition smoother)
//    public static final Animation ANIM_HAMSTER_PLAYDEAD = Animation.Builder.create(6.5f)
//            .addBoneAnimation("body",
//                    new Transformation(Transformation.Targets.TRANSLATE,
//                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1f, AnimationHelper.createTranslationalVector(0f, -1f, 0f),
//                                    Transformation.Interpolations.LINEAR)))
//            .addBoneAnimation("body",
//                    new Transformation(Transformation.Targets.ROTATE,
//                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(-129.32f, 23.93f, 26.34f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1f, AnimationHelper.createRotationalVector(-179.11f, 24.29f, -0.09f),
//                                    Transformation.Interpolations.LINEAR)))
//            .addBoneAnimation("head",
//                    new Transformation(Transformation.Targets.TRANSLATE,
//                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(0.125f, AnimationHelper.createTranslationalVector(0f, 1.58f, 1.2f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(0.25f, AnimationHelper.createTranslationalVector(0.6f, 1.75f, 2.4f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(0.375f, AnimationHelper.createTranslationalVector(1.2f, 1.13f, 3.6f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(2f, 0.1f, 4.8f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1f, AnimationHelper.createTranslationalVector(1.2f, -2.9f, 5.5f),
//                                    Transformation.Interpolations.LINEAR)))
//            .addBoneAnimation("head",
//                    new Transformation(Transformation.Targets.ROTATE,
//                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(-129.32f, 23.93f, 26.34f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1f, AnimationHelper.createRotationalVector(-179.11f, 24.29f, -0.09f),
//                                    Transformation.Interpolations.LINEAR)))
//            .addBoneAnimation("frontleg1",
//                    new Transformation(Transformation.Targets.TRANSLATE,
//                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(0.125f, AnimationHelper.createTranslationalVector(-0.32f, 1.9f, -0.37f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(0.25f, AnimationHelper.createTranslationalVector(-0.15f, 4.1f, 0.25f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(0.375f, AnimationHelper.createTranslationalVector(0.77f, 5.25f, 1.97f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(1.9f, 5.2f, 4.1f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(0.75f, AnimationHelper.createTranslationalVector(1.6f, 4.4f, 5.45f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1f, AnimationHelper.createTranslationalVector(1.5f, 3.2f, 6.6f),
//                                    Transformation.Interpolations.LINEAR)))
//            .addBoneAnimation("frontleg1",
//                    new Transformation(Transformation.Targets.ROTATE,
//                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(-129.32f, 23.93f, 26.34f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1f, AnimationHelper.createRotationalVector(-179.11f, 24.29f, -0.09f),
//                                    Transformation.Interpolations.LINEAR)))
//            .addBoneAnimation("backleg",
//                    new Transformation(Transformation.Targets.TRANSLATE,
//                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(0.125f, AnimationHelper.createTranslationalVector(-0.3f, -1.55f, -1.82f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(0.25f, AnimationHelper.createTranslationalVector(-1.2f, -2.3f, -4.45f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(0.375f, AnimationHelper.createTranslationalVector(-1.8f, -1.15f, -5.78f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(-2f, 1.4f, -6.9f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(0.75f, AnimationHelper.createTranslationalVector(-1.5f, 2.25f, -7.37f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1f, AnimationHelper.createTranslationalVector(-1.4f, 3.1f, -6.65f),
//                                    Transformation.Interpolations.LINEAR)))
//            .addBoneAnimation("backleg",
//                    new Transformation(Transformation.Targets.ROTATE,
//                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(-129.32f, 23.93f, 26.34f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1f, AnimationHelper.createRotationalVector(-179.11f, 24.29f, -0.09f),
//                                    Transformation.Interpolations.LINEAR)))
//            .addBoneAnimation("tail",
//                    new Transformation(Transformation.Targets.TRANSLATE,
//                            new Keyframe(0f, AnimationHelper.createTranslationalVector(0f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(0.5f, AnimationHelper.createTranslationalVector(-2f, -5.4f, -4.5f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1f, AnimationHelper.createTranslationalVector(-1.6f, -5.4f, -7f),
//                                    Transformation.Interpolations.LINEAR)))
//            .addBoneAnimation("tail",
//                    new Transformation(Transformation.Targets.ROTATE,
//                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(-129.32f, 23.93f, 26.34f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1f, AnimationHelper.createRotationalVector(-179.11f, 24.29f, -0.09f),
//                                    Transformation.Interpolations.LINEAR)))
//            .addBoneAnimation("leftleg",
//                    new Transformation(Transformation.Targets.ROTATE,
//                            new Keyframe(1f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1.25f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1.75f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(2f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(2.25f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(2.5f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(3f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(3.5f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(4f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(4.5f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(5.5f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(6.5f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR)))
//            .addBoneAnimation("rightleg",
//                    new Transformation(Transformation.Targets.ROTATE,
//                            new Keyframe(1f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1.25f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1.75f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(2f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(2.25f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(2.5f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(3f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(3.5f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(4f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(4.5f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(5.5f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(6.5f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR)))
//            .addBoneAnimation("rightleg2",
//                    new Transformation(Transformation.Targets.ROTATE,
//                            new Keyframe(1f, AnimationHelper.createRotationalVector(5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1.25f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1.75f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(2f, AnimationHelper.createRotationalVector(5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(2.25f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(2.5f, AnimationHelper.createRotationalVector(5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(3f, AnimationHelper.createRotationalVector(-5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(3.5f, AnimationHelper.createRotationalVector(5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(4f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(4.5f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(5.5f, AnimationHelper.createRotationalVector(-10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(6.5f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR)))
//            .addBoneAnimation("leftleg2",
//                    new Transformation(Transformation.Targets.ROTATE,
//                            new Keyframe(1f, AnimationHelper.createRotationalVector(-12.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1.25f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(-12.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(1.75f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(2f, AnimationHelper.createRotationalVector(-12.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(2.25f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(2.5f, AnimationHelper.createRotationalVector(-12.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(3f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(3.5f, AnimationHelper.createRotationalVector(-12.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(4f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(4.5f, AnimationHelper.createRotationalVector(-12.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(5.5f, AnimationHelper.createRotationalVector(10f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR),
//                            new Keyframe(6.5f, AnimationHelper.createRotationalVector(-12.5f, 0f, 0f),
//                                    Transformation.Interpolations.LINEAR))).build();

